name: EMBED SCRIPTS INTO MARKDOWN

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

jobs:
  embed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Start Job
        run: echo Started build
      - name: Install modules
        run: npm install
      - name: embed
        run: npm run embed
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          committer_name: GitHub Actions
          message: 'Added embeded scripts'
      - name: End Job
        run: echo End Job!

